// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ProductManagementDbContext))]
    [Migration("20240415164743_UpdateApprovalStatus")]
    partial class UpdateApprovalStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationCore.Entities.ApprovalRequest", b =>
                {
                    b.Property<int>("ApprovalRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalRequestId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ApprovalRequestId");

                    b.HasIndex("ProductId");

                    b.ToTable("ApprovalRequest");

                    b.HasData(
                        new
                        {
                            ApprovalRequestId = 1,
                            ProductId = 7,
                            RequestDate = new DateTime(2024, 3, 21, 9, 47, 43, 718, DateTimeKind.Local).AddTicks(8500),
                            RequestReason = "New product",
                            RequestType = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Gadget 1",
                            PostedDate = new DateTime(2024, 4, 13, 9, 47, 43, 718, DateTimeKind.Local).AddTicks(8400),
                            Price = 496.39999999999998
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Widget 2",
                            PostedDate = new DateTime(2023, 11, 15, 9, 47, 43, 718, DateTimeKind.Local).AddTicks(8470),
                            Price = 464.82999999999998
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Doohickey 3",
                            PostedDate = new DateTime(2024, 1, 8, 9, 47, 43, 718, DateTimeKind.Local).AddTicks(8470),
                            Price = 347.99000000000001
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Thingamajig 4",
                            PostedDate = new DateTime(2023, 10, 28, 9, 47, 43, 718, DateTimeKind.Local).AddTicks(8470),
                            Price = 13.279999999999999
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Thingamajig 5",
                            PostedDate = new DateTime(2023, 12, 8, 9, 47, 43, 718, DateTimeKind.Local).AddTicks(8480),
                            Price = 715.78999999999996
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Thingamajig 6",
                            PostedDate = new DateTime(2023, 8, 26, 9, 47, 43, 718, DateTimeKind.Local).AddTicks(8490),
                            Price = 611.51999999999998
                        },
                        new
                        {
                            Id = 7,
                            IsActive = false,
                            Name = "Thingamajig 7",
                            PostedDate = new DateTime(2023, 9, 9, 9, 47, 43, 718, DateTimeKind.Local).AddTicks(8490),
                            Price = 94.170000000000002
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Thingamajig 8",
                            PostedDate = new DateTime(2023, 8, 18, 9, 47, 43, 718, DateTimeKind.Local).AddTicks(8500),
                            Price = 545.02999999999997
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Thingamajig 9",
                            PostedDate = new DateTime(2023, 12, 16, 9, 47, 43, 718, DateTimeKind.Local).AddTicks(8510),
                            Price = 534.91999999999996
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Widget 10",
                            PostedDate = new DateTime(2023, 5, 25, 9, 47, 43, 718, DateTimeKind.Local).AddTicks(8510),
                            Price = 978.16999999999996
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.ApprovalRequest", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
